package com.per.product.enums;

public enum FragranceFamily {
    // Amber
    WOODY_AMBER,
    AMBER,
    SOFT_AMBER,

    // Florals
    FRUITY,
    FLORAL,
    SOFT_FLORAL,
    FLORAL_ALDEHYDE,
    FLORAL_AMBER,
    FLORAL_CHYPRE,
    FLORAL_FOUGERE,
    FLORAL_FRESH,
    FLORAL_FRUITY,
    FLORAL_ORIENTAL,
    FLORAL_WOODY,
    WHITE_FLORAL,

    // Fresh
    WATER,
    AROMATIC,
    AROMATIC_AQUATIC,
    AROMATIC_FOUGERE,
    AROMATIC_FRESH,
    GREEN,
    CITRUS,
    CITRUS_AROMATIC,
    FRESH_AQUATIC,
    FRESH_FLORAL,
    FRESH_GREEN,
    FRESH_ORIENTAL,

    // Woody
    MOSSY_WOODS,
    WOODS,
    DRY_WOODS,
    WOODY_AROMATIC,
    WOODY_FLORAL_MUSK,
    WOODY_MUSK,
    WOODY_ORIENTAL,
    WOODY_SPICY,

    // Oriental & Fruity
    FRUITY_CHYPRE,
    ORIENTAL_FLORAL,
    ORIENTAL_FOUGERE,
    ORIENTAL_FRESH,
    ORIENTAL_GOURMAND,
    ORIENTAL_SPICY,
    ORIENTAL_VANILLA
}
