package com.per.product.enums;

public enum Occasion {
    DAILY,
    EVENING,
    FORMAL,
    CASUAL,
    PARTY,
    BUSINESS_CASUAL,
    BUSINESS_EVENING,
    CASUAL_BUSINESS,
    CASUAL_DAYTIME,
    CASUAL_EVENING,
    EVENING_BUSINESS,
    EVENING_CASUAL,
    EVENING_FORMAL,
    EVENING_PARTY,
    EVENING_SPECIAL
}
